### ISSUE TITLE
some links are broken.

### ISSUE THREAD

**Issue by pol-den** [Urmuz/Yii2-All-For-Development#1]
some links are broken. for example https://github.com/ericmaicon/yii2-repository-patt...

**Comment by Urmuz** [comment]
No problem. I r

**Comment by Urmuz** [comment]
Thanks

**Comment by pol-den** [comment]
more errors. all links with three dots on end
https://github.com/nepster-web/yii2-extensions-ins...
https://github.com/2amigos/yii2-packagist-componen...
https://github.com/samdark/yii2-cookbook/blob/mast...
